// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface AboutFields {}

export interface About extends OstDocument<AboutFields> {}

export type AboutField = keyof About
