// Generated by Outstatic - do not edit manually

import type { Posts, PostsFields } from './posts'
import type { About, AboutFields } from './_singletons/about'

export type CollectionName = 'posts'

export type SingletonName = 'about'

export interface Collections {
  'posts': Posts
}

export interface Singletons {
  'about': About
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = PostsFields | AboutFields
